name: Java Lint, Build and Test Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
  workflow_dispatch: 

jobs:
  build-lint-test:
    name: Build, Lint, and Test Java Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download JUnit
        run: |
          curl -LJO https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.1/junit-platform-console-standalone-1.8.1.jar

      - name: Compile Java files
        run: |
          mkdir -p out/production out/test
          javac -d out/production $(find src -name "*.java")
          javac -d out/test -cp out/production $(find test -name "*.java")

      - name: Run Checkstyle
        run: |
          curl -LJO https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.2/checkstyle-10.12.2-all.jar
          java -jar checkstyle-10.12.2-all.jar -c /google_checks.xml $(find src -name "*.java")

      - name: Run JUnit tests
        run: |
          java -jar junit-platform-console-standalone-1.8.1.jar --class-path "out/test:out/production" --scan-class-path
      